package codeintel

import (
	"strings"
	"testing"
	"unicode/utf8"
)

// cabecera_test.go custodia QUÉ comentario se vuelve el resumen automático de un archivo. El error
// caro no es devolver "": es devolver el comentario equivocado, porque se guarda como el gist del
// archivo y un agente lo lee como «esto es lo que hace el archivo».

// Sabotaje: dejar de excluir los comentarios que son el doc de una declaración. El caso «pegado a
// la primera func» devuelve el doc de Foo como si fuera el resumen del archivo y la prueba cae.
// arnes: archivo="internal/codeintel/cabecera.go"
// arnes: de="\t\tif deDeclaracion[cg] {\n\t\t\tcontinue\n\t\t}\n"
// arnes: a="\t\tif deDeclaracion[cg] && false {\n\t\t\tcontinue\n\t\t}\n"
func TestResumenDeCabeceraNoRobaElDocDeLaPrimeraFuncion(t *testing.T) {
	casos := []struct {
		nombre, path, src, quiere string
	}{
		{"el doc del paquete manda", "pkg/a.go",
			"// Package pkg arma cosas.\n//\n// Segundo párrafo que no va.\npackage pkg\n\nfunc Foo() {}\n",
			"Package pkg arma cosas."},
		{"un bloque libre después de los imports (la forma de capture.go)", "pkg/a.go",
			"package pkg\n\nimport \"fmt\"\n\n// a.go hace X: lo que dice el archivo\n// en dos líneas.\n\n// Foo imprime.\nfunc Foo() { fmt.Println() }\n",
			"a.go hace X: lo que dice el archivo en dos líneas."},
		{"el comentario pegado a la primera func es de la func, no del archivo", "pkg/a.go",
			"package pkg\n\n// Foo hace algo que no es el resumen del archivo.\nfunc Foo() {}\n",
			""},
		{"un comentario después de la primera declaración no es cabecera", "pkg/a.go",
			"package pkg\n\nvar x = 1\n\n// suelto al medio del archivo.\n\nfunc Foo() {}\n",
			""},
		{"sólo directivas de build", "pkg/a.go",
			"//go:build linux\n// +build linux\n\npackage pkg\n\nfunc Foo() {}\n",
			""},
		{"el aviso de código generado no es un resumen", "pkg/a.go",
			"package pkg\n\n// Code generated by stringer; DO NOT EDIT.\n\n// z.go son los nombres.\n\nvar x = 1\n",
			"z.go son los nombres."},
		{"un comentario de adentro del bloque de imports no es cabecera", "pkg/a.go",
			"package pkg\n\nimport (\n\t\"fmt\"\n\n\t// suelto entre imports\n)\n\nfunc Foo() { fmt.Println() }\n",
			""},
		{"lo que no es Go no recibe resumen", "src/a.ts",
			"// a.ts hace X\nexport const a = 1\n",
			""},
		{"un _test.go no recibe resumen aunque tenga cabecera", "pkg/a_test.go",
			"// Package pkg prueba cosas.\npackage pkg\n",
			""},
	}
	for _, c := range casos {
		t.Run(c.nombre, func(t *testing.T) {
			if got := ResumenDeCabecera(c.path, c.src); got != c.quiere {
				t.Errorf("ResumenDeCabecera = %q, quería %q", got, c.quiere)
			}
		})
	}
}

// Sabotaje: sacar la excepción de los _test.go. Los ~280 tests con cabecera de Musubi reciben
// gist automático y el caso del _test.go de esta prueba devuelve su comentario.
// arnes: archivo="internal/codeintel/cabecera.go"
// arnes: de="|| strings.HasSuffix(base, \"_test.go\") {"
// arnes: a="|| strings.HasSuffix(base, \"_test.go.nunca\") {"
func TestLosTestsNoRecibenResumenAutomatico(t *testing.T) {
	src := "// a_test.go custodia X.\npackage pkg\n\n// Package-level libre.\n\nfunc TestX() {}\n"
	if got := ResumenDeCabecera("pkg/a_test.go", src); got != "" {
		t.Errorf("un _test.go recibió resumen %q: la decisión es no inundar code_memory con los tests", got)
	}
	// Y el mismo contenido en un archivo de producción SÍ recibe: la exclusión es por nombre, no
	// porque el extractor no entienda el archivo.
	if got := ResumenDeCabecera("pkg/a.go", src); got == "" {
		t.Error("el control no dio resumen: la prueba no estaría midiendo la exclusión de los tests")
	}
}

// Sabotaje: sacar el tope. Un comentario de cabecera largo se guarda entero como gist.
// arnes: archivo="internal/codeintel/cabecera.go"
// arnes: de="if utf8.RuneCountInString(r) > topeResumenDeCabecera {"
// arnes: a="if utf8.RuneCountInString(r) > topeResumenDeCabecera*100 {"
func TestElResumenDeCabeceraEsUnTitularConTope(t *testing.T) {
	largo := strings.Repeat("palabra ", 200)
	got := ResumenDeCabecera("pkg/a.go", "// "+largo+"\npackage pkg\n")
	if n := utf8.RuneCountInString(got); n > topeResumenDeCabecera {
		t.Errorf("el resumen mide %d runas, el tope es %d", n, topeResumenDeCabecera)
	}
	if !strings.HasSuffix(got, "…") {
		t.Errorf("un resumen recortado tiene que decir que lo está, terminó en %q", got[len(got)-10:])
	}
}
